title: Bild

columns:
  main:
    width: 1/2
    sections:
      content:
        type: fields
        fields:
          caption:
            label: Bildlegende
            type: textarea
            size: medium
  sidebar:
    width: 1/2
    sections:
      meta:
        type: fields
        fields:
          alt:
            label: Alternativer Text
            type: text
            required: true
            help: Kurze Textbeschreibung des Bildes. Für accessibility (z.B. blinde Personen) und Suchmaschinenoptimierung.
          photographer:
            label: Fotograf/in
            type: text
            width: 2/3
          license:
            label: Lizenz
            type: select
            width: 1/3
            options:
              - Proprietary
              - Unsplash
          link:
            label: Link
            type: url
