title: Home

tabs:
  Inhalt:
    columns:
      left:
        width: 2/3
        fields:
          headertext:
            label: Header Text
            type: writer
            required: true
            marks:
              - link
      right:
        width: 1/3
        sections:
          drafts:
            extends: sections/defaultpost
            headline: News - Entwurf
            status: draft
          unlisted:
            extends: sections/defaultpost
            headline: News - Unlisted
            status: unlisted
          listed:
            extends: sections/defaultpost
            headline: News - Publiziert
            status: listed      
  Meta:         
    fields:
      seo: fields/seo
